version: "2"
services:
  nginx:
      build:
        context: ./nginx
      ports:
          - "81:80"
      links:
          - fpm:fpm
          - mysql:mysql
      volumes:
          - ./app/:/var/www/html
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app/:/var/www/html
      ports:
          - '9001:9000'
      links:
          - mysql:mysql
      environment:
          - "DB_HOST=mysql"
          - "DB_DATABASE=surveydb"
  mysql:
      image: mariadb
      ports:
          - '3307:3306'
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=surveydb
      volumes:
          - ./database:/var/lib/mysql
          - ./app/:/var/www/html
  


    
